heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
  - http://elasticsearch:9200
  - http://kibana:5601
  - http://app:8000

- type: icmp
  schedule: '@every 5s'
  hosts:
  - elasticsearch
  - kibana
  - apm-server
  - metricbeat
  - minha-api
  - oracle-db

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: 'elasticsearch:9200'
  username: 'elastic'
  password: 'teste123'
setup.kibana:
  host: "http://kibana:5601"