INSERT INTO public.data_dictionary 
    (dd_schema, dd_table, dd_column, dd_type, dd_size, dd_specifications, dd_note)
VALUES
    ('public', 'data_dictionary', 'dd_id', 'INTEGER', 0, 'PRIMARY KEY DEFAULT NEXTVAL("seq_id_general") ','Id de identificação do registro.'),
    ('public', 'data_dictionary', 'dd_schema', 'VARCHAR', 50, 'NOT NULL ','Identificação do Schema ao qual a tabela pertence.'),
    ('public', 'data_dictionary', 'dd_table', 'VARCHAR', 50, 'NOT NULL ','Identificação da Tabela ao qual o campo pertence.'),
    ('public', 'data_dictionary', 'dd_column', 'VARCHAR', 50, 'NOT NULL ','Nome do campo.'),
    ('public', 'data_dictionary', 'dd_type', 'VARCHAR', 100, 'NOT NULL ','Tipo do campo.'),
    ('public', 'data_dictionary', 'dd_size', 'INTEGER', 0, 'NOT NULL ','Tamanho do campo. Observação: Quando o tipo for diferente de Varchar o valor será 0.'),
    ('public', 'data_dictionary', 'dd_note', 'VARCHAR', 1000, 'NOT NULL ','Informações pertinentes ao campo. Normalmente se encontra comentado ao lado de cada campo.'),
    ('public', 'origem_dados', 'od_id', 'SERIAL', 0, 'NOT NULL PRIMARY KEY ','Identificador do local de origem dos dados.'),
    ('public', 'origem_dados', 'od_local', 'VARCHAR', 20, 'NOT NULL ','Local de origem do dados exemplo: Planilha API etc.'),
    ('public', 'origem_dados', 'od_observacao', 'VARCHAR', 1000, '','Observações pertinentes sobre o local um exemplo seria nome do arquivo de origem.'),
    ('public', 'tipo_veiculo', 'tv_id', 'SERIAL', 0, 'NOT NULL PRIMARY KEY ','Id de Identificação do tipo de veiculo.'),
    ('public', 'tipo_veiculo', 'tv_tipo', 'VARCHAR', 50, 'NOT NULL ','Tipo do veiculo.'),
    ('public', 'tipo_veiculo', 'tv_observacoes', 'VARCHAR', 1000, '','Observações sobre o tipo do veiculo.'),
    ('public', 'marca_veiculo(', 'mv_id', 'SERIAL', 0, 'NOT NULL PRIMARY KEY ','Id de identificação da marca do veiculo.'),
    ('public', 'marca_veiculo(', 'mv_marca', 'VARCHAR', 30, 'NOT NULL ','Marca do veiculo.'),
    ('public', 'marca_veiculo(', 'mv_observacoes', 'VARCHAR', 1000, '','Observações sobre a marca do veiculo.'),
    ('public', 'modelo_veiculo', 'mov_id', 'SERIAL', 0, 'NOT NULL PRIMARY KEY ','Id de identificação do modelo do veiculo.'),
    ('public', 'modelo_veiculo', 'mov_modelo', 'VARCHAR', 30, 'NOT NULL ','Modelo do veiculo.'),
    ('public', 'modelo_veiculo', 'mov_observacoes', 'VARCHAR', 1000, '','Observações sobre o modelo do veiculo.'),
    ('public', 'cor_veiculo', 'cv_id', 'SERIAL', 0, 'NOT NULL PRIMARY KEY ','Id de identificação da cor do veiculo'),
    ('public', 'cor_veiculo', 'cv_cor', 'VARCHAR', 30, 'NOT NULL ','Cor predominate do veiculo.'),
    ('public', 'cor_veiculo', 'cv_observacoes', 'VARCHAR', 1000, '','Observações sobre a cor do veiculo.'),
    ('public', 'municipio', 'mu_id', 'SERIAL', 0, 'NOT NULL PRIMARY KEY ','Id de identificação do municipio.'),
    ('public', 'municipio', 'mu_nome', 'VARCHAR', 100, 'NOT NULL ','Nome do município.'),
    ('public', 'municipio', 'mu_uf', 'VARCHAR', 2, 'NOT NULL ','Unidade Federativa ao qual o Município Pertence.'),
    ('public', 'municipio', 'mu_observacao', 'VARCHAR', 1000, '','Observações quanto ao município.'),
    ('public', 'tipo_restricao', 'tr_id', 'SERIAL', 0, 'NOT NULL PRIMARY KEY ','Id de identificação do tipo de restrição'),
    ('public', 'tipo_restricao', 'tr_tipo', 'VARCHAR', 30, 'NOT NULL ','Tipo de restrição. Exemplo: Busca e Apreensão.'),
    ('public', 'tipo_restricao', 'tr_observacao', 'VARCHAR', 1000, '','Observação do tipo de restrição.'),
    ('public', 'tipo_ocorrencia', 'to_id', 'BIGSERIAL', 0, 'NOT NULL PRIMARY KEY ','Id de identificação do tipo de ocorrência.'),
    ('public', 'tipo_ocorrencia', 'to_codigo', 'VARCHAR', 10, 'NOT NULL ','Código de identificação do tipo de Ocorrência. Observação: Esse campo foi baseado no campo disponivel pela CELEPAR.'),
    ('public', 'tipo_ocorrencia', 'to_tipo', 'VARCHAR', 20, 'NOT NULL ','Tipo de ocorrência.'),
    ('public', 'tipo_ocorrencia', 'to_observacao', 'VARCHAR', 1000, '','Observação do tipo de ocorrência.'),
    ('public', 'tipo_notificacao', 'tn_id', 'SERIAL', 0, 'NOT NULL PRIMARY KEY ','Id de identificação no sistema do tipo de notificação.'),
    ('public', 'tipo_notificacao', 'tn_tipo', 'VARCHAR', 20, 'NOT NULL ','Tipo de notificação.'),
    ('public', 'tipo_notificacao', 'tn_observacao', 'VARCHAR', 1000, '','Observação sobre tipo de notificação.'),
    ('sc_alertas', 'dados_veiculo', 'dv_geo_id', 'BIGSERIAL', 0, 'NOT NULL PRIMARY KEY ','Geo Id de identificação do veiculo.'),
    ('sc_alertas', 'dados_veiculo', 'dv_numero_ocorrencias', 'INTEGER', 0, 'NOT NULL ','Número de ocorrências de comprote do veículo.'),
    ('sc_alertas', 'dados_veiculo', 'dv_ultima_atualizacao', 'DATE', 0, 'NOT NULL DEFAULT now() ','Data da ultima atualização de dados vinculado ao veículo.'),
    ('sc_alertas', 'dados_veiculo', 'dv_descricao_atualizacao', 'VARCHAR', 1000, '','Descrição da ultima atualização de dados vinculado ao veículo.'),
    ('sc_alertas', 'dados_veiculo', 'dv_pontos_criticidade', 'INTEGER', 0, 'NOT NULL DEFAULT 0 ','Pontos de criticidade do veículo. Observação: Esse ponto é definido baseado em uma série de regras e calculado por um IA.'),
    ('sc_alertas', 'dados_veiculo', 'dv_status', 'VARCHAR', 100, 'NOT NULL ','Status do veículo.'),
    ('sc_alertas', 'dados_veiculo', 'tv_id', 'INT', 0, 'NOT NULL ','Identificador do Tipo de Veiculo.'),
    ('sc_alertas', 'dados_veiculo', 'cv_id', 'INT', 0, 'NOT NULL ','Identificador da Cor do veiculo. Observação: Pode existir mais de uma cor em um veiculo nesse caso seria a cor predominante ou cores fantasias adesivados etc.'),
    ('sc_alertas', 'dados_veiculo', 'mv_id', 'INT', 0, 'NOT NULL ','Identificador da Marca do Veiculo.'),
    ('sc_alertas', 'dados_veiculo', 'mov_id', 'INT', 0, 'NOT NULL ','Identifica o Modelo do veiculo.'),
    ('sc_alertas', 'dados_veiculo', 'mu_id', 'INT', 0, 'NOT NULL ','Identificador do municipio ao qual o veículo está associado.'),
    ('sc_alertas', 'dados_veiculo', 'od_id', 'INT', 0, 'NOT NULL ','Identificação do local de importação do dado (Se foi importada de planilha API"s ou via sistema).'),
    ('sc_alertas', 'dados_camera', 'dc_id', 'SERIAL', 0, 'NOT NULL PRIMARY KEY ','Id de identificação da câmera no sistema.'),
    ('sc_alertas', 'dados_camera', 'dc_identificador', 'VARCHAR', 100, 'NOT NULL ','Identificador da camera. Observação: Diferente de ID esse identificador é a nomenclatura dada à câmera.'),
    ('sc_alertas', 'dados_camera', 'dc_latitude', 'DOUBLE PRECISION', 0, 'NOT NULL ','Latitude de georreferenciamento da localização da câmera.'),
    ('sc_alertas', 'dados_camera', 'dc_longitude', 'DOUBLE PRECISION', 0, 'NOT NULL ','Longitude de georreferenciamento da localização da câmera.'),
    ('sc_alertas', 'dados_camera', 'dc_localizacao', 'GEOMETRY(POINT)', 0, '','Campo GEOMETRY do PostGis para apresentação quartesiana da geolocalização da câmera. Observação: Utiliza a Latitude e Longitude.'),
    ('sc_alertas', 'dados_camera', 'dc_sentido', 'VARCHAR', 20, 'NOT NULL ','Identificação do sentido ao qual a câmera está apontada.'),
    ('sc_alertas', 'dados_camera', 'dc_data_cadastro', 'TIMESTAMP WITH TIME ZONE', 0, 'NOT NULL DEFAULT now() ','Data de quando o cadastro foi realizado.'),
    ('sc_alertas', 'dados_camera', 'dc_ativa', 'BOOLEAN', 0, 'NOT NULL DEFAULT true ','Identificação se a câmera continua ativa.'),
    ('sc_alertas', 'dados_camera', 'dc_observacao', 'VARCHAR', 1000, '','Informações adicionais sobre a câmera.'),
    ('sc_alertas', 'dados_camera', 'od_id', 'INT', 0, 'NOT NULL ','Identificação do local de importação do dado (Se foi importada de planilha API"s ou via sistema).'),
    ('sc_alertas', 'notificacao', 'no_id', 'BIGSERIAL', 0, 'NOT NULL PRIMARY KEY ','ID de Identificação do registro no sistema.'),
    ('sc_alertas', 'notificacao', 'no_latitude', 'DOUBLE PRECISION', 0, 'NOT NULL ','Latitude de georreferenciamento da localização da notificação.'),
    ('sc_alertas', 'notificacao', 'no_longitude', 'DOUBLE PRECISION', 0, 'NOT NULL ','Longitude de georreferenciamento da localização da notificação.'),
    ('sc_alertas', 'notificacao', 'no_localizacao', 'GEOMETRY(POINT)', 0, '','Campo GEOMETRY do PostGis para apresentação quartesiana da geolocalização da notificação. Observação: Utiliza a Latitude e Longitude.'),
    ('sc_alertas', 'notificacao', 'no_origem_notificacao', 'VARCHAR', 20, '','Identifica a origem da notificação. Exemplo: Agente Câmera etc.'),
    ('sc_alertas', 'notificacao', 'no_observacao', 'VARCHAR', 1000, '','Observação da notificação.'),
    ('sc_alertas', 'notificacao', 'no_hora', 'TIME', 0, 'NOT NULL DEFAULT now() ','Horário de emissão da notificação.'),
    ('sc_alertas', 'notificacao', 'no_data', 'DATE', 0, 'NOT NULL DEFAULT now() ','Data de emissão da notificação.'),
    ('sc_alertas', 'notificacao', 'no_ativa', 'BOOLEAN', 0, 'NOT NULL DEFAULT true ','Status da notificação.'),
    ('sc_alertas', 'notificacao', 'nc_status_visualizacao', 'INTEGER', 0, 'NOT NULL DEFAULT 0 ','Identifica o status de visualização da notificação. Observação: 0 - Notificação não lida 1 - Notificação apenas visualizada no painel de notificação 2 - Notificação lida.'),
    ('sc_alertas', 'notificacao', 'ag_id_visualizacao', 'INTEGER', 0, '','Agente que visualizou a notificação no sistema.'),
    ('sc_alertas', 'notificacao', 'ag_id', 'INTEGER', 0, '','Id de identificação do agente emitente da notificação.'),
    ('sc_alertas', 'notificacao', 'dc_id', 'INTEGER', 0, '','Id de identificação da camera emitente da notificação.'),
    ('sc_alertas', 'notificacao', 'tn_id', 'INTEGER', 0, 'NOT NULL ','Id de identificação do tipo de notificação.'),
    ('sc_alertas', 'notificacao', 'od_id', 'INT', 0, 'NOT NULL ','Identificação do local de importação do dado (Se foi importada de planilha API"s ou via sistema).'),
    ('sc_alertas', 'imagem_notificacao', 'in_id', 'BIGSERIAL', 0, 'NOT NULL PRIMARY KEY ','Id de identificação do registro no sistema.'),
    ('sc_alertas', 'imagem_notificacao', 'in_imagem', 'BYTEA', 0, 'NOT NULL ','Imagem armazenada em modo BYTEA.'),
    ('sc_alertas', 'imagem_notificacao', 'no_id', 'BIGINT', 0, 'NOT NULL ','Id de identificação da notificação ao qual a imagem está associada.'),
    ('sc_alertas', 'lista_notificacoes_ativas', 'no_id', 'BIGINT', 0, 'NOT NULL PRIMARY KEY ','Id de identificação da notificação será usada como Primary Key desta Tabela. Observação: A tabela lista_notificacoes_ativas será populada apenas por Trigger sendo usada apenas para consultas.'),
    ('sc_alertas', 'lista_notificacoes_ativas', 'lna_latitude', 'DOUBLE PRECISION', 0, 'NOT NULL ','Latitude de georreferenciamento da localização da notificação.'),
    ('sc_alertas', 'lista_notificacoes_ativas', 'lna_longitude', 'DOUBLE PRECISION', 0, 'NOT NULL ','Longitude de georreferenciamento da localização da notificação.'),
    ('sc_alertas', 'lista_notificacoes_ativas', 'lna_localizacao', 'GEOMETRY(POINT)', 0, 'NOT NULL ','Campo GEOMETRY do PostGis para apresentação quartesiana da geolocalização da notificação. Observação: Utiliza a Latitude e Longitude.'),
    ('sc_alertas', 'lista_notificacoes_ativas', 'lna_camera', 'BOOLEAN', 0, 'NOT NULL ','Identifica se a notificação está associada a uma câmera.'),
    ('sc_alertas', 'lista_notificacoes_ativas', 'dc_id', 'INTEGER', 0, '','Id de identificação da câmera caso o registro esteja associado a uma.');
